WEAPONS = {
    "Rapière": {
        "name": "Rapière",
        "damage": "1d8",
        "category": "Heavy",
        "desc": "C'est une belle rapière en bon état !",
    },
    "Dague": {
        "name": "Dague",
        "damage": "1d4",
        "category": "Light",
        "desc": "Cette dague m'a l'air de renfermer un secret !",
    },
    "Marteau de guerre": {
        "name": "Marteau de guerre",
        "damage": "1d8",
        "category": "Heavy",
        "desc": "Le sang des ennemies semble encore frais sur cette arme",
    },
    "Marteau léger": {
        "name": "Marteau",
        "damage": "1d6",
        "category": "Light",
        "desc": "Je suis un marteau !",
    },
    "Arbalète": {
        "name": "Arbalète",
        "damage": "1d8",
        "category": "Light",
        "desc": "Vise la tête !",
    },
    "Décharge Occulte": {
        "name": "Décharge Occulte",
        "damage": "1d10",
        "category": "Magic",
        "desc": "A qui sont ces os ?",
    },
    "Murmures Dissonants": {
        "name": "Murmures Dissonants",
        "damage": "3d6",
        "category": "Magic",
        "desc": "Qui me parle ?",
    },
    "Contact Glacial": {
        "name": "Contact Glacial",
        "damage": "1d8",
        "category": "Magic",
        "desc": "Ouhla... fait frisquet ici !",
    },
    "Morsure de dragon": {
        "name": "Morsure de dragon",
        "damage": "1d10",
        "category": "Monster",
        "desc": "Miam...",
    },
    "Souffle d'acide": {
        "name": "Souffle d'acide",
        "damage": "4d8",
        "category": "Monster",
        "desc": "C'est moi ou vous êtes en train de vous dissoudre ?",
    },
    "Griffe de bête sauvage": {
        "name": "Griffe de bête sauvage",
        "damage": "2d6",
        "category": "Monster",
        "desc": "je vous fais une manucure ?",
    },
    "Morsure de bête sauvage": {
        "name": "Morsure de bête sauvage",
        "damage": "2d6",
        "category": "Monster",
        "desc": "Miam...",
    },
    "Griffe de goule": {
        "name": "Griffe de goule",
        "damage": "2d4",
        "category": "Monster",
        "desc": "Je vous fais une manucure ?",
    },
    "Morsure de goule": {
        "name": "Morsure de goule",
        "damage": "2d6",
        "category": "Monster",
        "desc": "Miam...",
    },
    "Absorbtion de vie": {
        "name": "Absorbtion de vie",
        "damage": "3d6",
        "category": "Monster",
        "desc": "La vie est comme un jeu vidéo, je collecte les vies.",
    },
    "Vaporisation d'acide": {
        "name": "Vaporisation d'acide",
        "damage": "3d6",
        "category": "Monster",
        "desc": "Ah mais qui à laché une caisse ?",
    },
    "Coup de bec": {
        "name": "Coup de bec",
        "damage": "1d8",
        "category": "Monster",
        "desc": "Picoti et picota...",
    },
    "Morsure de mimique": {
        "name": "Morsure de mimique",
        "damage": "1d8",
        "category": "Monster",
        "desc": "Miam...",
    },
    "Pseudopode": {
        "name": "Pseudopode",
        "damage": "1d8",
        "category": "Monster",
        "desc": "Miam...",
    },
    "Morsure de merrow": {
        "name": "Morsure de merrow",
        "damage": "1d8",
        "category": "Monster",
        "desc": "Miam...",
    },
    "Harpon": {
        "name": "Harpon",
        "damage": "2d6",
        "category": "Monster",
        "desc": "Qui va à la chasse perd sa place, qui va à la pêche...",
    },
    "Coup": {
        "name": "Coup",
        "damage": "1d6",
        "category": "Monster",
        "desc": "Aïe !",
    },
    "Attaque surprise": {
        "name": "Attaque surprise",
        "damage": "3d6",
        "category": "Monster",
        "desc": "Coucou... BEUH !",
    },
    "Morsure de basilic": {
        "name": "Morsure de basilic",
        "damage": "4d6",
        "category": "Monster",
        "desc": "Ca mort le Pesto ?",
    },
    "Epée longue": {
        "name": "Epée longue",
        "damage": "1d8",
        "category": "Heavy",
        "desc": "En guarde !",
    },
    "Arbalète lourde": {
        "name": "Arbalète lourde",
        "damage": "1d10",
        "category": "Heavy",
        "desc": "Attention, faut pas loucher !",
    },
}
